### ISSUE TITLE
Using directory structures

### ISSUE THREAD

**Issue by rschwalk** [serenevoid/kiwi.nvim#10]
I structure my notes in one wiki, but in a directory structure. At the moment *kiwi.nvim* try to always use the main wiki directory. I need to define a path manually: 
`[diary](./diary/diary.md)`
Then if I create links in the diary.md, they will be created also under the main path. The link `[entry](./entry.md)` doesn't construct the file under the directory "diary" as a ./ suggest. 

If directory structures should be supported then two option is possible:
If the actual `.md` is in a sub directory 
1. then the `[entry](./entry.md)` should be created in the same directory 
2. or the directory should be added to the path `[entry](./diary/entry.md)`

**Comment by serenevoid** [comment]
Thanks for the suggestion. I think kitsugo's PR adds this feature. I'll check it out.
