### ISSUE TITLE
Helpfile missing

### ISSUE THREAD

**Issue by mcjvanschaik** [serenevoid/kiwi.nvim#14]
I might be the very first user that doesn´t have experience with Vimwiki that tries kiwi.nvim.

After installation I automatically entered :he kiwi, but then I saw the same readme and it wasn´t pleasant to read.

I have tried to make a first version for the help file. Would you like me to send a pull request for it?

**Comment by serenevoid** [comment]
I haven't thought about adding a help file for kiwi.nvim till now since its a straightforward and simple plugin. But it is better to have a good help file for future use. I appreciate your interest in developing it. And yes I would love to have your PR.
