### ISSUE TITLE
Duplication of path on new entry creation (MacOS)

### ISSUE THREAD

**Issue by avastmick** [serenevoid/kiwi.nvim#21]
While this plugin looks promising, I cannot get it work as expected with more than one notes location.

My configuration:

```lua
return {
    'serenevoid/kiwi.nvim',
    dependencies = {
        "nvim-lua/plenary.nvim"
    },
    opts = {
        {
            name = "work",
            path = "/Users/avastmick/notes/edu-docs"
        },
        {
            name = "personal",
            path = "/Users/avastmick/notes/local-notes"
        }
    },
    keys = {
        { "<leader>kw", ":lua require(\"kiwi\").open_wiki_index(\"work\")<cr>",     desc = "Open Wiki index" },
        { "<leader>kp", ":lua require(\"kiwi\").open_wiki_index(\"personal\")<cr>", desc = "Open index of personal wiki" },
        { "T",          ":lua require(\"kiwi\").todo.toggle()<cr>",                 desc = "Toggle Markdown Task" }
    },
    lazy = true
}
```

Usage:

I open the `personal` and add in a line 'Daily Plan', select words and <CR>, I get the following path (see the status line)

![image](https://github.com/serenevoid/kiwi.nvim/assets/16931995/2425c1c9-5ca1-4c6c-8ec6-c24dc64ca3ad)

I hit `Ctrl+o` to return to `index.md`, hovered link does not show duplicated path elements:

![image](https://github.com/serenevoid/kiwi.nvim/assets/16931995/8c5efff7-9c9e-4e2c-9b21-09a7140c67f2)

If I remove the leading `./` from the new link, <CR> navigates to a new file in the directory I opened `nvim`.

**Comment by avastmick** [comment]
Sorry, update, the behaviour is now regardless of the number of wiki locations: I thought it was working for one, but it was actually creating files in the wrong place.

**Comment by serenevoid** [comment]
Hi @avastmick! Thanks for reporting this issue.  I have two questions though.
- Is the index file created in the correct location for these two wiki locations? 
- This path trimming is failing only when the notes are created from the wiki note?

**Comment by avastmick** [comment]
> Hi @avastmick! Thanks for reporting this issue. I have two questions though.
> 
> * Is the index file created in the correct location for these two wiki locations?
> * This path trimming is failing only when the notes are created from the wiki note?

Firstly, yes, an index.md is created.

Next, I may I know the issue... I have imported markdown notes from another source and these are in a hierarchy, rather than flat. If I create two new wikis and allow `kiwi` to create a new `index.md` and create from there in a flat structure, then there are no issues.

So, to confirm, only a flat Wiki structure is supported right now..? I couldn't have something like:

```
.
├── architecture
│   └── index.md
├── business_planning
│   ├── Data_Needs.md
│   ├── Deployment_Needs.md
│   ├── Roadmap_Needs.md
│   ├── Security_Needs.md
│   ├── index.md
│   └── oAuth_authentication.md
├── index.md
├── operations
│   └── index.md
├── roadmap.md
└── security
    ├── Information_security_management_system_(ISMS).md
    └── index.md

```
Thanks for the work on this and getting back so promptly on the issue I raised. The issue may be found between the computer and the user 😀

**Comment by serenevoid** [comment]
Thank you for the details! I could reproduce the issue. Will update the plugin soon!
And to answer your questions, 
- No, its not caused by your plugins clashing since I could reproduce it
- Yes, the plugin is currently meant for flat directory structure since that is easier for fast wiki note creation. But you could create a custom wiki link by typing the proper path from the wiki directory and use it as normal. You can't create notes in custom subdirectories. That's all

**Comment by avastmick** [comment]
Thanks for resolving. Great stuff!

**Comment by tarurata** [comment]
@avastmick 


It seems the variable "relative_path" includes "config.path", which is the absolute path to each wiki, such as "path like path = '/Users/testuser/personal-wiki'" on Mac.
Therefore, "relative_path" works as an absolute path.

To bypass this issue for now, I overwrote the method "utils.get_relative_path" as shown below in "init.vim".
(Of course, you can simplify it further by returning empty strings without an if clause.)

```lua
lua << EOF
-- https://github.com/serenevoid/kiwi.nvim/issues/21
local utils = require'kiwi.utils'

local is_windows = vim.loop.os_uname().version:match('Windows')

utils.get_relative_path = function (config)
    local relative_path = vim.fs.dirname(vim.fn.expand('%:p'))
    if is_windows then
        -- For Windows, replace backslashes with forward slashes in the config path
        return relative_path:gsub(config.path:gsub("\\", "/"), "")
    else
        -- For macOS, return the relative path directly
        return ""
    end
end
EOF

```

**Comment by serenevoid** [comment]
@avastmick I have added a new commit for fixing this issue. 
Please have a look when you find time. 
Hope to hear from you soon.

**Comment by mlwarner** [comment]
The latest change broke my setup using Obsidian and iCloud. I think this line in `ensure_directories`:

```lua
props.path = props.path:gsub("$HOME", get_home()):gsub("~", get_home())
```

conflicts with my config:

```lua
            local wikiPath = '/Users/mwarner/Library/Mobile Documents/iCloud~md~obsidian/Documents/my_notes'
            require('kiwi').setup({
                {
                    name = 'personal',
                    path = wikiPath,
                },
            })
```

**Comment by serenevoid** [comment]
@mlwarner Thanks for your response. I have rolled back the plugin. Please try updating the plugin again.

**Comment by mlwarner** [comment]
Thanks! I unpinned the commit and it is working as expected.

I think you are looking for path expansion here rather than a substitution. Quick scan through vim help docs has `vim.fn.expand`. Testing with `:lua =vim.fn.expand("/Users/mwarner/Library/Mobile Documents/iCloud~md~obsidian/Documents/my_notes")` yields the same path, and `:lua vim.fn.expand("~/wiki") also works as expected.

**Comment by maximilianZenke** [comment]
I do not know if this is the right place for this issue, as I am not on MacOS. However, I seem to have the same issue: If I create links to new notes inside my index.md, I can not save the new notes because the path to my wiki is dublicated. 
![image](https://github.com/user-attachments/assets/60534c1f-ae3c-454e-9957-fb4e50c15847)

**Comment by serenevoid** [comment]
Ooh. I have been thinking of removing the absolute path for wikis. Users can provide a directory or subdirectory from their home directory. So just `path = "wiki"` will be considered as `$HOME/wiki` in windows and `~/wiki/` in unix systems. Hope that works for everyone.
