### ISSUE TITLE
Support opening web links

### ISSUE THREAD

**Issue by ssdaniel24** [serenevoid/kiwi.nvim#22]
Example:
```markdown
[cool guy who made kiwi.nvim](https://github.com/serenevoid)
                      ^ cursor somewhere here
```
hitting Enter should run `$ xdg-open https://github.com/serenevoid`.

**Comment by serenevoid** [comment]
This looks cool. But if the functionality already exists in that plugin, will it work alongside kiwi? Just wanted to check to keep kiwi leaner.

**Comment by serenevoid** [comment]
It definitely is a good feature. I'll test it out in the future. Also, there is this default keymap `gf` in normal mode from Vim that opens the URL under the cursor in your default web browser. So if this feature is useful for many people, I'll consider it. Thanks for the suggestion!
