### ISSUE TITLE
<Leader>ww and <Leader>wp are only working after "T" was executed once 

### ISSUE THREAD

**Issue by maximilianZenke** [serenevoid/kiwi.nvim#24]
I initialized kiwi.lvim in my config.lua like this 
```lua
lvim.plugins = {
  {
    'serenevoid/kiwi.nvim',
    dependencies = {
        "nvim-lua/plenary.nvim"
    },
    opts = {
        {
            name = "work",
            path = "C:\\Users\\Max\\personal-wiki"
        },
    },
    keys = {
        { "<leader>ww", ":lua require(\"kiwi\").open_wiki_index()<cr>", desc = "Open Wiki index" },
        { "<leader>wp", ":lua require(\"kiwi\").open_wiki_index(\"personal\")<cr>", desc = "Open index of personal wiki" },
        { "T", ":lua require(\"kiwi\").todo.toggle()<cr>", desc = "Toggle Markdown Task" },
    },
    lazy = true
  },
... other plugins ...  
```
After successfully installing the plugin, I try to use `<Leader>ww` or  `<Leader>wp` to open my wiki index(es), which I doublechecked does in fact exist at the given location. 

## Expected behaviour 

`<Leader>ww` or `<Leader>wp` open my wiki index

## Actual behavior 

`<Leader>ww` or `<Leader>wp` do not open anything. 

## Steps to reproduce 
- ( use windows? *I do not know if this matters*)
- Install the plugin using the default configuration. Adjust the opts.path for windows following the documentation 
- Close vim 
- Open vim 
- Execute `<Leader>ww` or `<Leader>wp`
- *nothing happens* 

## Workaround 

Calling the plugin in any way **before** trying to execute either `<Leader>ww` or `<Leader>wp`, for example by the `"T"` command or a custom command like `"{ "!", ":lua require(\"kiwi\")", desc ="activate kiwi" }` does resolve the issue. **After** executing those commands, `<Leader>ww` and `<Leader>wp' work as intended

**Comment by maximilianZenke** [comment]
I do not quite understand why this happens, but toying around with my config made me realize that everythign works as intended if I re-map the keybindings to something else than "ww" and "wp".  I am unsure if this is a problem on my end

**Comment by maximilianZenke** [comment]
I do not quite understand why this happens, but toying around with my config made me realize that everythign works as intended if I re-map the keybindings to something else than "ww" and "wp".  I am unsure if this is a problem on my end

**Comment by serenevoid** [comment]
Hi. I didn't notice this issue until today since it was closed. I see that this is your first issue on GitHub!
I use Windows at work, and it does work it my system as intended. So, I think it is more of a config issue.
Can you check if ww and wp are getting over-written buy some other keymap?
If you have telescope installed, try `:Telescope keymaps`.
