### ISSUE TITLE
Using kiwi for all ".md" files

### ISSUE THREAD

**Issue by TheJayGatsby** [serenevoid/kiwi.nvim#26]
Hi,

  I am using kiwi.nvim and I think it is incredible. 

  However, I was not able to configure it to use it with standalone markdown files, it only works after I call the open_wiki_index function. From that point on, no problem.

  But what if I want to open and edit an markdown file that doesn't belong to an particular wiki? Is it possible to make kiwi.nvim to work that way?

Thanks!

**Comment by serenevoid** [comment]
Thanks! And no as of now, the keymaps and features of kiwi are only inside kiwi.
The todo toggle will work on all markdown files outside kiwi too. 
But we can think about making keymaps for things that you like to work outside kiwi. Let me know which ones you like to be available on all markdown files

**Comment by serenevoid** [comment]
These keymaps can work outside kiwi.
```lua
local opts = { noremap = true, silent = true, nowait = true }
vim.keymap.set("n", "<CR>", ":lua require(\"kiwi\").open_link()<CR>", opts)
vim.keymap.set("n", "<Tab>", ":let @/=\"\\\\[.\\\\{-}\\\\]\"<CR>nl", opts) -- Jump to next link
vim.keymap.set("T", ":lua require(\"kiwi\").todo.toggle()<cr>", opts)
```
If you want this to be applicable to all markdown files, you can add these keymaps to `.config/nvim/ftplugin/markdown.lua`.
